Traceback (most recent call last):
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/dsmith4/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
p = [[0,0,0],
[1,1,1],
[2,1,2],
[3,0,3]]
fig, (ax1, ax2) = plt.subplots(1, 2)
fig.suptitle('Creation and Destruction of a Muon')
ax1.plot(p[:,0], p[:,1], 'k:')
ax2.plot(p[1:2,0], p[1:2,1], 'r-')
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 7[0m
[1;32m      5[0m fig, (ax1, ax2) [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m1[39m, [38;5;241m2[39m)
[1;32m      6[0m fig[38;5;241m.[39msuptitle([38;5;124m'[39m[38;5;124mCreation and Destruction of a Muon[39m[38;5;124m'[39m)
[0;32m----> 7[0m ax1[38;5;241m.[39mplot([43mp[49m[43m[[49m[43m:[49m[43m,[49m[38;5;241;43m0[39;49m[43m][49m, p[:,[38;5;241m1[39m], [38;5;124m'[39m[38;5;124mk:[39m[38;5;124m'[39m)
[1;32m      8[0m ax2[38;5;241m.[39mplot(p[[38;5;241m1[39m:[38;5;241m2[39m,[38;5;241m0[39m], p[[38;5;241m1[39m:[38;5;241m2[39m,[38;5;241m1[39m], [38;5;124m'[39m[38;5;124mr-[39m[38;5;124m'[39m)
[1;32m      9[0m plt[38;5;241m.[39mshow()

[0;31mTypeError[0m: list indices must be integers or slices, not tuple
TypeError: list indices must be integers or slices, not tuple

