Traceback (most recent call last):
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/dsmith4/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/dsmith4/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# ST plot of object passing observer
def lm(b,ct,x):
    g = 1/np.sqrt(1-b**2)
    ctp = g*(ct-b*x)
    xp = g*(x0-b*ct)
    return(ctp,xp)

xrest = np.zeros((3,1))+0.3
yrest = np.arange(3)*1.7/3.0
beta = .55
xfront = np.arange(0,.5,.1)
yfront = 0.75-xfront/beta
xback = np.arange(0,1.0,.2)
yback = 1.45-xback/beta
yrest,xrest = lm(-beta,yrest,xrest)

plt.figure(figsize=(5,5))
plt.arrow(0,0,1,0,head_width=0.1)
plt.arrow(0,0,0,1,head_width=0.1)

plt.arrow(-0.5,-0.5,1,0,head_width=0.1)
plt.arrow(-0.5,-0.5,0,1,head_width=0.1)

plt.arrow(0.9,-0.25,-0.75,0,head_width=0.05)

plt.plot(xrest,yrest,'r-')
plt.plot(xfront,yfront,'g-')
plt.plot(xback,yback,'b-')

ax = plt.gca()
ax.get_xaxis().set_visible(False)
ax.get_yaxis().set_visible(False)
plt.axis([-1,2,-1,2])
ax.text(0.85, 1, "S")
ax.text(-0.05, 1.2, "ct")
ax.text(1.2, 0, "x")
ax.text(1.1, -0.25, "v_R")
ax.text(-0.35, .5, "S'")
ax.text(-.55, .7, "ct'")
ax.text(.7, -0.5, "x'")
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 15[0m
[1;32m     13[0m xback [38;5;241m=[39m np[38;5;241m.[39marange([38;5;241m0[39m,[38;5;241m1.0[39m,[38;5;241m.2[39m)
[1;32m     14[0m yback [38;5;241m=[39m [38;5;241m1.45[39m[38;5;241m-[39mxback[38;5;241m/[39mbeta
[0;32m---> 15[0m yrest,xrest [38;5;241m=[39m [43mlm[49m[43m([49m[38;5;241;43m-[39;49m[43mbeta[49m[43m,[49m[43myrest[49m[43m,[49m[43mxrest[49m[43m)[49m
[1;32m     17[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m5[39m,[38;5;241m5[39m))
[1;32m     18[0m plt[38;5;241m.[39marrow([38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m1[39m,[38;5;241m0[39m,head_width[38;5;241m=[39m[38;5;241m0.1[39m)

Cell [0;32mIn[5], line 5[0m, in [0;36mlm[0;34m(b, ct, x)[0m
[1;32m      3[0m g [38;5;241m=[39m [38;5;241m1[39m[38;5;241m/[39mnp[38;5;241m.[39msqrt([38;5;241m1[39m[38;5;241m-[39mb[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m)
[1;32m      4[0m ctp [38;5;241m=[39m g[38;5;241m*[39m(ct[38;5;241m-[39mb[38;5;241m*[39mx)
[0;32m----> 5[0m xp [38;5;241m=[39m g[38;5;241m*[39m([43mx0[49m[38;5;241m-[39mb[38;5;241m*[39mct)
[1;32m      6[0m [38;5;28;01mreturn[39;00m(ctp,xp)

[0;31mNameError[0m: name 'x0' is not defined
NameError: name 'x0' is not defined

